disabled builds

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -38,156 +38,156 @@ jobs:
           name: otp_git_archive
           path: otp_src.tar.gz
 
-  build:
-    name: Build Erlang/OTP
-    runs-on: ubuntu-latest
-    needs: pack
+  # build:
+  #   name: Build Erlang/OTP
+  #   runs-on: ubuntu-latest
+  #   needs: pack
 
-    strategy:
-      matrix:
-        type: [64-bit,32-bit,cross-compile,documentation]
-      fail-fast: false
+  #   strategy:
+  #     matrix:
+  #       type: [64-bit,32-bit,cross-compile,documentation]
+  #     fail-fast: false
 
-    steps:
-      - uses: actions/checkout@v2
-      - name: Download source archive
-        uses: actions/download-artifact@v2
-        with:
-          name: otp_git_archive
-      - name: Docker login
-        uses: docker/login-action@v1
-        with:
-          registry: docker.pkg.github.com
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Calculate BASE image
-        id: base
-        run: |
-          BASE_TAG=$(grep "^FROM" .github/dockerfiles/Dockerfile.${{ matrix.type }} | head -1 | awk '{print $2}')
-          echo "::set-output name=BASE_TAG::${BASE_TAG}"
-          .github/scripts/base-tag "${BASE_TAG}"
-      - name: Pull BASE image
-        run: docker pull ${{ steps.base.outputs.BASE_TAG }}
-      - name: Build BASE image
-        run: |
-          docker build --pull --tag ${{ steps.base.outputs.BASE_TAG }} \
-            --cache-from ${{ steps.base.outputs.BASE_TAG }} \
-            --file .github/dockerfiles/Dockerfile.${{ steps.base.outputs.BASE_TYPE }} \
-            --build-arg BASE=${{ steps.base.outputs.BASE }} .
-      - name: Build ${{ matrix.type }} image
-        run: |
-          docker build --tag otp --file .github/dockerfiles/Dockerfile.${{ matrix.type }} \
-            --build-arg ARCHIVE=otp_src.tar.gz .
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Download source archive
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: otp_git_archive
+  #     - name: Docker login
+  #       uses: docker/login-action@v1
+  #       with:
+  #         registry: docker.pkg.github.com
+  #         username: ${{ github.repository_owner }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Calculate BASE image
+  #       id: base
+  #       run: |
+  #         BASE_TAG=$(grep "^FROM" .github/dockerfiles/Dockerfile.${{ matrix.type }} | head -1 | awk '{print $2}')
+  #         echo "::set-output name=BASE_TAG::${BASE_TAG}"
+  #         .github/scripts/base-tag "${BASE_TAG}"
+  #     - name: Pull BASE image
+  #       run: docker pull ${{ steps.base.outputs.BASE_TAG }}
+  #     - name: Build BASE image
+  #       run: |
+  #         docker build --pull --tag ${{ steps.base.outputs.BASE_TAG }} \
+  #           --cache-from ${{ steps.base.outputs.BASE_TAG }} \
+  #           --file .github/dockerfiles/Dockerfile.${{ steps.base.outputs.BASE_TYPE }} \
+  #           --build-arg BASE=${{ steps.base.outputs.BASE }} .
+  #     - name: Build ${{ matrix.type }} image
+  #       run: |
+  #         docker build --tag otp --file .github/dockerfiles/Dockerfile.${{ matrix.type }} \
+  #           --build-arg ARCHIVE=otp_src.tar.gz .
 
-        ## Smoke build tests
-      - if: matrix.type == '32-bit' || matrix.type == '64-bit' || matrix.type == 'cross-compile'
-        name: Run smoke test
-        run: docker run -v $PWD/scripts:/scripts otp "cd /tests && /scripts/run-smoke-tests"
+  #       ## Smoke build tests
+  #     - if: matrix.type == '32-bit' || matrix.type == '64-bit' || matrix.type == 'cross-compile'
+  #       name: Run smoke test
+  #       run: docker run -v $PWD/scripts:/scripts otp "cd /tests && /scripts/run-smoke-tests"
 
-        ## Documentation checks
-      - if: matrix.type == 'documentation'
-        name: Run xmllimt
-        run: docker run otp "make xmllint"
-      - if: matrix.type == 'documentation'
-        name: Run html link check
-        run: docker run -v $PWD/scripts:/scripts otp "/scripts/otp_html_check /otp doc/index.html"
-      - if: matrix.type == 'documentation'
-        name: Release docs to publish
-        run: .github/scripts/release-docs.sh
-      - if: matrix.type == 'documentation'
-        name: Upload html documentation archive
-        uses: actions/upload-artifact@v2
-        with:
-          name: otp_doc_html
-          path: otp_doc_html.tar.gz
-      - if: matrix.type == 'documentation'
-        name: Upload man documentation archive
-        uses: actions/upload-artifact@v2
-        with:
-          name: otp_doc_man
-          path: otp_doc_man.tar.gz
+  #       ## Documentation checks
+  #     - if: matrix.type == 'documentation'
+  #       name: Run xmllimt
+  #       run: docker run otp "make xmllint"
+  #     - if: matrix.type == 'documentation'
+  #       name: Run html link check
+  #       run: docker run -v $PWD/scripts:/scripts otp "/scripts/otp_html_check /otp doc/index.html"
+  #     - if: matrix.type == 'documentation'
+  #       name: Release docs to publish
+  #       run: .github/scripts/release-docs.sh
+  #     - if: matrix.type == 'documentation'
+  #       name: Upload html documentation archive
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: otp_doc_html
+  #         path: otp_doc_html.tar.gz
+  #     - if: matrix.type == 'documentation'
+  #       name: Upload man documentation archive
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: otp_doc_man
+  #         path: otp_doc_man.tar.gz
 
-        ## Check formatting of cpp code
-      - if: matrix.type == '64-bit'
-        name: Check format
-        run: docker run -v $PWD/scripts:/scripts otp "make format-check"
-        ## Run dialyzer
-      - if: matrix.type == '64-bit'
-        name: Run dialyzer
-        run: docker run -v $PWD/scripts:/scripts otp "/scripts/run-dialyzer"
+  #       ## Check formatting of cpp code
+  #     - if: matrix.type == '64-bit'
+  #       name: Check format
+  #       run: docker run -v $PWD/scripts:/scripts otp "make format-check"
+  #       ## Run dialyzer
+  #     - if: matrix.type == '64-bit'
+  #       name: Run dialyzer
+  #       run: docker run -v $PWD/scripts:/scripts otp "/scripts/run-dialyzer"
 
-        ## Build pre-built tar archives
-      - if: matrix.type == '32-bit'
-        name: Build pre-built tar archives
-        run: |
-          docker run -v $PWD:/github otp \
-          "scripts/build-otp-tar -o /github/otp_clean_src.tar.gz /github/otp_src.tar.gz -b /buildroot/otp/ /buildroot/otp.tar.gz"
-      - if: matrix.type == '32-bit'
-        name: Upload pre-built tar archive
-        uses: actions/upload-artifact@v2
-        with:
-          name: otp_prebuilt
-          path: otp_src.tar.gz
+  #       ## Build pre-built tar archives
+  #     - if: matrix.type == '32-bit'
+  #       name: Build pre-built tar archives
+  #       run: |
+  #         docker run -v $PWD:/github otp \
+  #         "scripts/build-otp-tar -o /github/otp_clean_src.tar.gz /github/otp_src.tar.gz -b /buildroot/otp/ /buildroot/otp.tar.gz"
+  #     - if: matrix.type == '32-bit'
+  #       name: Upload pre-built tar archive
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: otp_prebuilt
+  #         path: otp_src.tar.gz
 
-  ## If this is a tag that has been pushed we do some release work
-  release:
-    name: Release Erlang/OTP
-    runs-on: ubuntu-latest
-    needs: build
-    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'erlang/otp'
-    steps:
-      ## This step outputs the tag name and whether the tag is a release or patch
-      ## (all releases have only two version identifiers, while patches have three
-      ##  or more)
-      - name: Get Tag Name
-        id: tag
-        run: |
-          TAG=${GITHUB_REF#refs/tags/}
-          IS_RELEASE=`$(echo $TAG | grep -E '^OTP-[0-9]+\.[0-9]+$' > /dev/null) \
-            && echo "true" || echo "false"`
-          echo "::set-output name=tag::${TAG}"
-          echo "::set-output name=release::${IS_RELEASE}"
+  # ## If this is a tag that has been pushed we do some release work
+  # release:
+  #   name: Release Erlang/OTP
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   if: startsWith(github.ref, 'refs/tags/') && github.repository == 'erlang/otp'
+  #   steps:
+  #     ## This step outputs the tag name and whether the tag is a release or patch
+  #     ## (all releases have only two version identifiers, while patches have three
+  #     ##  or more)
+  #     - name: Get Tag Name
+  #       id: tag
+  #       run: |
+  #         TAG=${GITHUB_REF#refs/tags/}
+  #         IS_RELEASE=`$(echo $TAG | grep -E '^OTP-[0-9]+\.[0-9]+$' > /dev/null) \
+  #           && echo "true" || echo "false"`
+  #         echo "::set-output name=tag::${TAG}"
+  #         echo "::set-output name=release::${IS_RELEASE}"
       
-      - uses: actions/checkout@v2
+  #     - uses: actions/checkout@v2
 
-      ## Publish the pre-built archive and docs
-      - name: Download source archive
-        uses: actions/download-artifact@v2
-        with:
-          name: otp_prebuilt
-      - name: Download html docs
-        uses: actions/download-artifact@v2
-        with:
-          name: otp_doc_html
-      - name: Download man docs
-        uses: actions/download-artifact@v2
-        with:
-          name: otp_doc_man
+  #     ## Publish the pre-built archive and docs
+  #     - name: Download source archive
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: otp_prebuilt
+  #     - name: Download html docs
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: otp_doc_html
+  #     - name: Download man docs
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: otp_doc_man
 
-      ## We add the correct version name into the file names
-      ## and create the hash files for all assets
-      - name: Create pre-build and doc archives
-        run: .github/scripts/create-artifacts.sh artifacts ${{ steps.tag.outputs.tag }}
+  #     ## We add the correct version name into the file names
+  #     ## and create the hash files for all assets
+  #     - name: Create pre-build and doc archives
+  #       run: .github/scripts/create-artifacts.sh artifacts ${{ steps.tag.outputs.tag }}
 
-      - name: Build OTP Bundle
-        if: steps.tag.outputs.release == 'true'
-        run: |
-          scripts/bundle-otp ${{ steps.tag.outputs.tag }}
+  #     - name: Build OTP Bundle
+  #       if: steps.tag.outputs.release == 'true'
+  #       run: |
+  #         scripts/bundle-otp ${{ steps.tag.outputs.tag }}
 
-      ## Create hash files
-      - name: Create pre-build and doc archives
-        run: |
-          shopt -s nullglob
-          cd artifacts
-          md5sum {*.tar.gz,*.txt} > MD5.txt
-          sha256sum {*.tar.gz,*.txt} > SHA256.txt
+  #     ## Create hash files
+  #     - name: Create pre-build and doc archives
+  #       run: |
+  #         shopt -s nullglob
+  #         cd artifacts
+  #         md5sum {*.tar.gz,*.txt} > MD5.txt
+  #         sha256sum {*.tar.gz,*.txt} > SHA256.txt
 
-      - name: Upload pre-built and doc tar archives
-        uses: softprops/action-gh-release@v1
-        with:
-          name: OTP ${{ steps.tag.outputs.vsn }}
-          files: |
-            artifacts/*.tar.gz
-            artifacts/*.txt
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Upload pre-built and doc tar archives
+  #       uses: softprops/action-gh-release@v1
+  #       with:
+  #         name: OTP ${{ steps.tag.outputs.vsn }}
+  #         files: |
+  #           artifacts/*.tar.gz
+  #           artifacts/*.txt
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
